from fastapi import FastAPI, UploadFile
import shutil
import pandas as pd
import plotly.express as px
import numpy as np
import requests

from backend.run_pipeline import run_pipeline

app = FastAPI()

@app.post("/upload")

async def upload_file(file: UploadFile):

    path = f"data/{file.filename}"

    with open(path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    # Run pipeline (Python + R)
    run_pipeline(path)

    # Load differential expression results
    df = pd.read_csv("results/differential_gene_results.csv")

    # Load top genes generated by R
    top_genes = pd.read_csv("results/top_genes.csv")

    # Volcano plot
    df["NegLogP"] = -np.log10(df["P.Value"])

    fig = px.scatter(
        df,
        x="logFC",
        y="NegLogP",
        hover_data=["gene_id"],
        title="Volcano Plot"
    )

    gene_list = top_genes["gene_id"].tolist()

    # Send genes to n8n AI workflow
    ai_response = requests.post(
        "http://localhost:5678/webhook/gene-analysis",
        json={"genes": gene_list}
    )

    ai_json = ai_response.json()


    ai_text = ai_json["analysis"]

    return {
        "plot": fig.to_json(),
        "genes": top_genes.to_dict(orient="records"),
        "ai": ai_text
    }